### ISSUE TITLE
获取歌曲详情失败

### ISSUE THREAD

**Issue by ZUOXIANGE** [jadepeng/music163tool#1]
1. 应该是歌单歌曲太多了导致的,我一个歌单有上千歌曲,我手动修改了程序减少单次获取数量就可以了.
2. 还有我想在获取用户信息的时候根据usertype判断是否是会员然后获取无版权歌曲歌曲的时候就跳过会员有权限的歌曲,但是没找到相关的接口说明,不知道怎么判断是否是会员歌曲.

**Comment by jadepeng** [comment]
你看下调用 /user/detail 的json返回，里面找找

**Comment by ZUOXIANGE** [comment]
不是,我不是判断不了是否是会员,我甚至可以自己加个checkbox自己选是否是会员.我现在的问题是不知道怎么判断歌曲是否是会员专享的

**Comment by ZUOXIANGE** [comment]
下班回家仔细看了下,发现这个条件就是判断歌曲是否收费的....
```csharp
songObj["fee"].Value<int>() == 1
```

**Comment by ZUOXIANGE** [comment]
感谢作者的贡献让我简单修改就实现了自己的需求
